# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InterChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '12.0'
  use_frameworks!

  # Pods for InterChallenge
  pod 'Alamofire', '~> 5.4'
  pod 'Kingfisher', '~> 7.0'


  target 'InterChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InterChallengeUITests' do
    # Pods for testing
  end

end
